deployments:
  - name: my-app-1
    image: nginx
    namespace: default
    port: 80
    resources:
      requests:
        cpu: "500m"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "512Mi"
  - name: my-app-2
    image: nginx
    namespace: default
    port: 80
    resources:
      requests:
        cpu: "500m"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "512Mi"

autoscalers:
  - deployment: my-app-1
    namespace: default
    minReplicas: 1
    maxReplicas: 5
    metric:
      type: cpu
      value: "50"
      metricType: Utilization
  - deployment: my-app-2
    namespace: default
    minReplicas: 2
    maxReplicas: 5
    trigger:
      type: "queue"
      metadata:
        queueName: "my-queue"
        queueLength: "10"

services:
  - name: my-app-1
    namespace: default
    port: 80
  - name: my-app-2
    namespace: default
    port: 80
